### ISSUE TITLE
actions doesnr work while playing.

### ISSUE THREAD

**Issue by fmkash** [Thanatoslayer6/clistream#1]
Actions menu doesnt show up and sometimes said 'reading (0)'

**Comment by fmkash** [comment]
![image](https://user-images.githubusercontent.com/99625534/204416081-cdef4254-3c82-4d16-9691-e4dc371aa203.png)

**Comment by Thanatoslayer6** [comment]
Good day!

Kindly update to version `v1.3.0`, it should be working now, as fixed from 3e89d5e75d9eeb494101e8846f4419948dd858d8
