### ISSUE TITLE
[Bug] [Q&A] `Select multiple subtitles · No items were selected`

### ISSUE THREAD

**Issue by bachig26** [Thanatoslayer6/clistream#2]
While moving to the subtitles section, I'm seeing options to select subtitle language like English, others but when I selected the the langauge, it shows `No items were selected`.
and no subtitles is added to the mpv stream.

**Comment by Thanatoslayer6** [comment]
Good day!

I've never encountered this issue but selecting subtitles by pressing 'Space' will do (you can select as many subtitles you want). For further information, this app uses [enquirer](https://www.npmjs.com/package/enquirer) which handles selection and prompting. 

I will close this issue now, please reopen if you wish to have any questions, that's all thanks :relieved:
