### ISSUE TITLE
[help] session file issue

### ISSUE THREAD

**Issue by bachig26** [Thanatoslayer6/clistream#4]
I'm always getting this message as you see the full lines from my previous opened issue `No session file found, will create one if user saves...`.

I find there is no files being saved in the config folder, please help me how to solve this and how can I create one as it been saying as I find there are no way to do so.

**Comment by Thanatoslayer6** [comment]
Good Day!

It is actually normal for you to have that output if you have no session file saved inside your config folder, if you wish to save a session when watching. You can always quit mpv by pressing 'q' then a prompt will ask you to save a session with its timestamp included (the moment you quit mpv). 

By running `clistream` again, it will check for a session file inside your config folder, and if it has a session file you can always return to that session quickly at a specific timestamp.

Again, i'll close this issue for now and if you wish to further ask questions kindly reopen this issue, that's all thanks 😌
